### ISSUE TITLE
(URGENT) "ISO/IEC DIR 2" Missing editions 3 to 8

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iso#16]
ISO/IEC DIR 2:2004 is cited in JIS Z 8301:2019:
* https://github.com/metanorma/mn-samples-jis/pull/20/commits/74fcfeb81a04fae73103ac94d338fa5e4ca7140a

We need to back fill all the editions.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, are you requesting to add the edition of "ISO/IEC DIR 2" reference in the Bibliography?

I mean, to change this:
```
* [[[ISO_IEC_Directives_Part_2,ISO/IEC DIR 2]]] ...
```
to this:
```
* [[[ISO_IEC_Directives_Part_2,ISO/IEC DIR 2:2004]]] ...
```

**Comment by ronaldtse** [comment]
@manuelfuenmayor not at all... I am asking to enter new bibliographic items that we can cite.

This repository is relaton-data-iso. It provides items that others can cite through Relaton.

Look at this directory:
https://github.com/relaton/relaton-data-iso/tree/main/data
<img width="303" alt="Screenshot 2023-11-22 at 9 44 59 AM" src="https://github.com/relaton/relaton-data-iso/assets/11865/0f5f1b40-236d-4ffe-928c-7a4e0a6104db">

ISO/IEC DIR 2 is missing all the editions from 2001 and 2021.

This task is to add them.

**Comment by manuelfuenmayor** [comment]
Thanks @ronaldtse.

Another comment:

> (URGENT) "ISO/IEC DIR 2" Missing editions 3 to 8

I believe the missing editions are from 5 to 8.
According to this [site](https://www.iso.org/resources/publicly-available-resources.html?t=dg_2pVuZlo9t0QU3tob4bB94oXlW5ScsRNMgzFw43Qq4CcVx7NZrlQf-5CG-tfXy&view=documents#section-isodocuments-topl). The version from 2001 corresponds to the fourth edition (not second).
