### ISSUE TITLE
Incorrect relations' IDs

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-data-iso#27]
We have static files that were created manually. Three of them have incorrect ID in their relation bib item.
https://github.com/relaton/relaton-data-iso/blob/84d0320e8d25cd4c261cb927d78ea20ae1479de6/static/ISO_IEC_DIR_1.yaml#L54
https://github.com/relaton/relaton-data-iso/blob/84d0320e8d25cd4c261cb927d78ea20ae1479de6/static/ISO_IEC_DIR_2.yaml#L54
https://github.com/relaton/relaton-data-iso/blob/84d0320e8d25cd4c261cb927d78ea20ae1479de6/static/ISO_IEC_DIR_3.yaml#L50

@ronaldtse can we fix them? The pubid-iso fails to parse these IDs.

**Comment by ronaldtse** [comment]
Can you explain how they're incorrect? Of course we can fix them.

**Comment by andrew2net** [comment]
@ronaldtse found, we discussed it earlier here https://github.com/relaton/relaton-iso/issues/144#issuecomment-1874972500
So I'm going to remover these relations.

**Comment by ronaldtse** [comment]
According to that comment, “ISO/IEC DIR” should not be a standalone PubID because “ISO/IEC TR” is also not a PubID. That makes sense, we can remove them.

**Comment by ronaldtse** [comment]
@andrew2net do we have a GHA validation check for this repository that all data is correct?

**Comment by andrew2net** [comment]
@ronaldtse we have validation check for static files which are made by hand https://github.com/relaton/relaton-data-iso/actions/workflows/check_data.yml
