### ISSUE TITLE
Add multiple editions of "ISO/IEC Directives Consolidated ISO Supplement"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iso#5]
@Darkod55 can you help add bibliographic YAML files for the multiple editions of the "ISO/IEC Directives Consolidated ISO Supplement"? Thanks!

```
iso_iec_dir_1_iso_sup_ed-13.yml (2022)
iso_iec_dir_1_iso_sup_ed-12.yml (2021)
iso_iec_dir_1_iso_sup_ed-11.yml (2020)
iso_iec_dir_1_iso_sup_ed-10.yml (2019)
...
```

**Comment by ronaldtse** [comment]
Thank you @Darkod55 for encoding them here. @relaton/editors can you please help verify these files? Thanks!
[Archive 2.zip](https://github.com/relaton/relaton-data-iso/files/8897379/Archive.2.zip)

**Comment by anermina** [comment]
Files are added in #6 along with markup corrections.

**Comment by ronaldtse** [comment]
Done in #26
