### ISSUE TITLE
Need to differentiate IEC Supplement, Consolidated IEC Supplement, Consolidated ISO Supplement

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iso#7]

**Comment by ronaldtse** [comment]
@andrew2net , what's the best way to do this?

**Comment by andrew2net** [comment]
@ronaldtse what is the purpose of the differentiation? If we need to see it in the references then we should rename files.

**Comment by ronaldtse** [comment]
Then we should just rename the files. Relaton will parse all files and the mark uniqueness based only on the docid? 

What is the effect of the file names?

**Comment by ronaldtse** [comment]
Done in #26
